version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - microservices-net
    
  eureka-server:
    build:
      context: ./services/eureka
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net

  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net

  api-gateway:
    build:
      context: ./services/gateway-service
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8070:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - microservices-net

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8071:8080"
    environment:
      JWT_SECRET: 63f4945d921d599f27ae4fdf5bada3f1
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/app_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
    networks:
      - microservices-net

volumes:
  postgres-data:

networks:
  microservices-net:
    driver: bridge