FROM maven:3.9-eclipse-temurin-25

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

# Copia apenas os arquivos do wrapper primeiro para aproveitar o cache de camadas
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copia o código fonte da aplicação
COPY src ./src

# Inicia o serviço Spring Boot apontando para o DevTools e escutando por alterações
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]